export const GAME_TITLE = "TwistedBlur";
export const VERSION = "0.1.0";

export const TARGET_WIDTH = 1600;
export const TARGET_HEIGHT = 900;
export const FIXED_DT = 1 / 60;
export const MAX_HUMAN_PLAYERS = 4;
export const MAX_COMPETITORS = 8;
export const WORLD_MARGIN = 220;

export const PLAYER_COLORS = [
  "#2ef0ff",
  "#ff6b2d",
  "#b7ff3b",
  "#ff58b7",
  "#ffd166",
  "#7f8cff",
  "#55f0b5",
  "#ff9558",
];

export const PLAYER_LABELS = ["P1", "P2", "P3", "P4"];

export const MODE_DEFS = {
  combatRace: {
    id: "combatRace",
    name: "Combat Race",
    description: "Three laps. First across the line wins while the pack unloads firepower.",
    laps: 3,
    timeLimit: 360,
    respawn: true,
    allowRaceHud: true,
    preferredCategory: "race",
  },
  arenaDeathmatch: {
    id: "arenaDeathmatch",
    name: "Arena Deathmatch",
    description: "Scrap for kills in a sealed arena. Hit the score target or own the timer.",
    killTarget: 8,
    timeLimit: 240,
    respawn: true,
    preferredCategory: "arena",
  },
  survival: {
    id: "survival",
    name: "Survival",
    description: "No respawns. A lethal storm escalates until the last machine still rolls.",
    timeLimit: 999,
    respawn: false,
    preferredCategory: "arena",
  },
  quickBattle: {
    id: "quickBattle",
    name: "Quick Battle",
    description: "Fast local chaos. Short timer, boosted pickups, immediate pressure.",
    killTarget: 5,
    timeLimit: 90,
    respawn: true,
    preferredCategory: "any",
  },
};

export const MODE_ORDER = Object.keys(MODE_DEFS);

export const VEHICLE_DEFS = [
  {
    id: "vector-lynx",
    name: "Vector Lynx",
    archetype: "Interceptor",
    speed: 560,
    acceleration: 400,
    handling: 2.85,
    armor: 110,
    boostCapacity: 120,
    traction: 0.95,
    mass: 1.0,
    radius: 34,
    bodyColor: "#2ef0ff",
    trimColor: "#b4fcff",
    description: "Fast turn-in and clean boost recovery.",
  },
  {
    id: "iron-jackal",
    name: "Iron Jackal",
    archetype: "Bruiser",
    speed: 500,
    acceleration: 340,
    handling: 2.25,
    armor: 155,
    boostCapacity: 90,
    traction: 0.88,
    mass: 1.32,
    radius: 38,
    bodyColor: "#ff6b2d",
    trimColor: "#ffd5b5",
    description: "Heavy nose, strong rams, shrugs off chip damage.",
  },
  {
    id: "nova-riot",
    name: "Nova Riot",
    archetype: "Street Rocket",
    speed: 585,
    acceleration: 380,
    handling: 2.65,
    armor: 100,
    boostCapacity: 135,
    traction: 0.9,
    mass: 0.96,
    radius: 33,
    bodyColor: "#b7ff3b",
    trimColor: "#efffb3",
    description: "Top speed specialist with volatile boost reserves.",
  },
  {
    id: "glacier-maw",
    name: "Glacier Maw",
    archetype: "Control Tank",
    speed: 460,
    acceleration: 315,
    handling: 2.1,
    armor: 170,
    boostCapacity: 85,
    traction: 1.02,
    mass: 1.4,
    radius: 40,
    bodyColor: "#7f8cff",
    trimColor: "#dce1ff",
    description: "Slowest shell, best stability, ideal on hostile surfaces.",
  },
  {
    id: "ion-viper",
    name: "Ion Viper",
    archetype: "Pulse Interceptor",
    speed: 590,
    acceleration: 392,
    handling: 2.92,
    armor: 104,
    boostCapacity: 128,
    traction: 0.94,
    mass: 0.98,
    radius: 34,
    bodyColor: "#1f87ff",
    trimColor: "#9dd8ff",
    spritePath: "../assets/images/ion-viper_left.png",
    spriteFacing: "left",
    spriteScale: 1.02,
    description: "Blue plasma coupe with sharp turn-in and violent boost pull.",
  },
  {
    id: "grim-hauler",
    name: "Grim Hauler",
    archetype: "Siege Truck",
    speed: 470,
    acceleration: 320,
    handling: 2.02,
    armor: 182,
    boostCapacity: 82,
    traction: 1.04,
    mass: 1.5,
    radius: 42,
    bodyColor: "#6f8a6f",
    trimColor: "#d6e6c7",
    spritePath: "../assets/images/grim-hauler_left.png",
    spriteFacing: "left",
    spriteScale: 1.08,
    description: "Armored gun-hauler built to pin rivals and survive the pileup.",
  },
  {
    id: "solar-fang",
    name: "Solar Fang",
    archetype: "Hyper Lance",
    speed: 612,
    acceleration: 410,
    handling: 2.78,
    armor: 96,
    boostCapacity: 146,
    traction: 0.89,
    mass: 0.92,
    radius: 32,
    bodyColor: "#ffbf24",
    trimColor: "#fff0a1",
    spritePath: "../assets/images/solar-fang_left.png",
    spriteFacing: "left",
    spriteScale: 1.01,
    description: "Gold strike-frame with absurd top end and almost no patience.",
  },
  {
    id: "riot-jackal",
    name: "Riot Jackal",
    archetype: "Raider Utility",
    speed: 520,
    acceleration: 360,
    handling: 2.38,
    armor: 146,
    boostCapacity: 98,
    traction: 0.96,
    mass: 1.26,
    radius: 38,
    bodyColor: "#ff8f1f",
    trimColor: "#ffe0a8",
    spritePath: "../assets/images/riot-jackal_right.png",
    spriteFacing: "right",
    spriteScale: 1.04,
    description: "Off-road jackal with stable exits, big elbows, and mean bump force.",
  },
  {
    id: "night-marshal",
    name: "Night Marshal",
    archetype: "Pursuit Enforcer",
    speed: 548,
    acceleration: 372,
    handling: 2.5,
    armor: 126,
    boostCapacity: 116,
    traction: 0.94,
    mass: 1.08,
    radius: 35,
    bodyColor: "#aeb7c6",
    trimColor: "#ffffff",
    spritePath: "../assets/images/night-marshal_left.png",
    spriteFacing: "left",
    spriteScale: 1.01,
    description: "Blacksite interceptor tuned for chase pressure and steady control.",
  },
  {
    id: "vanta-razor",
    name: "Vanta Razor",
    archetype: "Shadow Cutter",
    speed: 578,
    acceleration: 386,
    handling: 2.72,
    armor: 108,
    boostCapacity: 132,
    traction: 0.91,
    mass: 0.97,
    radius: 34,
    bodyColor: "#7b3cff",
    trimColor: "#d1afff",
    spritePath: "../assets/images/vanta-razor_left.png",
    spriteFacing: "left",
    spriteScale: 1.02,
    description: "Dark neon slicer with surgical lines and lethal recovery speed.",
  },
];

export const SPECIAL_WEAPON_DEFS = {
  rocket: {
    id: "rocket",
    name: "Rockets",
    icon: "RKT",
    ammo: 3,
    cooldown: 0.7,
    color: "#ff8b5d",
    description: "Straight explosive rockets with heavy splash.",
  },
  homing: {
    id: "homing",
    name: "Homing Missile",
    icon: "HMG",
    ammo: 2,
    cooldown: 1.0,
    color: "#ffd166",
    description: "Tracks the nearest target in front of the driver.",
  },
  mine: {
    id: "mine",
    name: "Mines",
    icon: "MIN",
    ammo: 2,
    cooldown: 0.45,
    color: "#ff4c63",
    description: "Drops contact mines that punish pursuit lines.",
  },
  emp: {
    id: "emp",
    name: "EMP Burst",
    icon: "EMP",
    ammo: 1,
    cooldown: 1.4,
    color: "#2ef0ff",
    description: "Disables nearby vehicles and scrambles momentum.",
  },
  shockwave: {
    id: "shockwave",
    name: "Shockwave",
    icon: "SHK",
    ammo: 1,
    cooldown: 1.1,
    color: "#b7ff3b",
    description: "Short-range radial blast for knockback and breathing room.",
  },
  shield: {
    id: "shield",
    name: "Shield",
    icon: "SHD",
    ammo: 1,
    cooldown: 4.0,
    color: "#6ec8ff",
    description: "Temporary barrier that blanks most incoming punishment.",
  },
  rail: {
    id: "rail",
    name: "Rail Lance",
    icon: "RIL",
    ammo: 1,
    cooldown: 1.15,
    color: "#9de9ff",
    description: "Piercing beam that punches through lined-up targets.",
  },
  flak: {
    id: "flak",
    name: "Flak Burst",
    icon: "FLK",
    ammo: 2,
    cooldown: 0.72,
    color: "#ffbe73",
    description: "Wide explosive scatter shot for point-blank chaos.",
  },
  arc: {
    id: "arc",
    name: "Arc Net",
    icon: "ARC",
    ammo: 1,
    cooldown: 1.0,
    color: "#8efcdf",
    description: "Chains crackling current through clustered opponents in front.",
  },
};

export const PICKUP_DEFS = {
  rocket: { id: "rocket", label: "Rockets", icon: "RKT", color: "#ff8b5d", kind: "weapon" },
  homing: { id: "homing", label: "Homing", icon: "HMG", color: "#ffd166", kind: "weapon" },
  mine: { id: "mine", label: "Mines", icon: "MIN", color: "#ff4c63", kind: "weapon" },
  emp: { id: "emp", label: "EMP", icon: "EMP", color: "#2ef0ff", kind: "weapon" },
  shockwave: { id: "shockwave", label: "Shock", icon: "SHK", color: "#b7ff3b", kind: "weapon" },
  shield: { id: "shield", label: "Shield", icon: "SHD", color: "#6ec8ff", kind: "weapon" },
  rail: { id: "rail", label: "Rail", icon: "RIL", color: "#9de9ff", kind: "weapon" },
  flak: { id: "flak", label: "Flak", icon: "FLK", color: "#ffbe73", kind: "weapon" },
  arc: { id: "arc", label: "Arc Net", icon: "ARC", color: "#8efcdf", kind: "weapon" },
  repair: { id: "repair", label: "Repair", icon: "RPR", color: "#45f3a8", kind: "support" },
  turbo: { id: "turbo", label: "Turbo", icon: "TRB", color: "#ff8be7", kind: "support" },
};

export const PICKUP_TABLE = [
  { id: "rocket", weight: 13 },
  { id: "homing", weight: 10 },
  { id: "mine", weight: 14 },
  { id: "emp", weight: 9 },
  { id: "shockwave", weight: 8 },
  { id: "shield", weight: 8 },
  { id: "rail", weight: 7 },
  { id: "flak", weight: 9 },
  { id: "arc", weight: 7 },
  { id: "repair", weight: 11 },
  { id: "turbo", weight: 13 },
];

export const KEYBOARD_LAYOUTS = [
  {
    label: "WASD",
    steerLeft: "KeyA",
    steerRight: "KeyD",
    accel: "KeyW",
    brake: "KeyS",
    fire: "Space",
    alt: "ShiftLeft",
    boost: "KeyQ",
    lookBack: "KeyE",
    pause: "Escape",
  },
  {
    label: "Arrows",
    steerLeft: "ArrowLeft",
    steerRight: "ArrowRight",
    accel: "ArrowUp",
    brake: "ArrowDown",
    fire: "Numpad0",
    alt: "Numpad1",
    boost: "Numpad2",
    lookBack: "Numpad3",
    pause: "Slash",
  },
  {
    label: "TFGH",
    steerLeft: "KeyF",
    steerRight: "KeyH",
    accel: "KeyT",
    brake: "KeyG",
    fire: "KeyR",
    alt: "KeyY",
    boost: "KeyV",
    lookBack: "KeyB",
    pause: "Digit0",
  },
  {
    label: "IJKL",
    steerLeft: "KeyJ",
    steerRight: "KeyL",
    accel: "KeyI",
    brake: "KeyK",
    fire: "KeyU",
    alt: "KeyO",
    boost: "KeyN",
    lookBack: "KeyM",
    pause: "Minus",
  },
];

export const MENU_KEYS = {
  up: ["ArrowUp", "KeyW"],
  down: ["ArrowDown", "KeyS"],
  left: ["ArrowLeft", "KeyA"],
  right: ["ArrowRight", "KeyD"],
  accept: ["Enter", "Space"],
  back: ["Backspace", "Escape"],
  addKeyboard2: ["Digit2"],
  addKeyboard3: ["Digit3"],
  addKeyboard4: ["Digit4"],
  removeLast: ["Delete"],
};

export const PHYSICS_TUNING = {
  worldDrag: 1.35,
  lateralGrip: 7.6,
  reverseSpeedFactor: 0.45,
  collisionPush: 0.5,
  collisionBounce: 0.76,
  vehicleImpactDamage: 0.041,
  offroadSpeedFactor: 0.74,
  offroadAccelFactor: 0.72,
  boostBurnRate: 33,
  passiveBoostRecharge: 12,
  lowHealthThreshold: 0.28,
  respawnDelay: 2.6,
  raceRespawnDelay: 2.0,
  steerResponse: 5.4,
  throttleResponse: 4.8,
  counterSteerAssist: 1.15,
  driftGripFactor: 0.64,
  driftTurnBonus: 0.28,
  forwardSnap: 1.95,
  impactBoostDamageFactor: 1.2,
};

export const UI_COLORS = {
  text: "#f4f8ff",
  dim: "#93a6c7",
  danger: "#ff4c63",
  good: "#45f3a8",
  accentHot: "#ff6b2d",
  accentCyan: "#2ef0ff",
  accentLime: "#b7ff3b",
  accentSteel: "#89a3d9",
  panel: "rgba(8, 13, 24, 0.72)",
  panelStrong: "rgba(7, 11, 19, 0.94)",
  panelGlass: "rgba(16, 24, 42, 0.58)",
  frame: "rgba(255, 255, 255, 0.12)",
  frameStrong: "rgba(255, 255, 255, 0.22)",
  shadow: "rgba(0, 0, 0, 0.34)",
  warning: "#ffd166",
};

export const CAMERA_TUNING = {
  baseZoom: 0.65,
  minZoom: 0.48,
  maxZoom: 0.82,
  speedZoomFactor: 0.00035,
  smoothing: 6.5,
  shakeDamping: 5.8,
};

export const PARTICLE_LIMITS = {
  particles: 1600,
  skidMarks: 220,
};

export const BOT_DIFFICULTIES = [
  { id: "rookie", name: "Rookie", throttle: 0.86, aim: 0.72, aggression: 0.58, recovery: 1.25, chase: 0.6, boostUse: 0.55 },
  { id: "street", name: "Street", throttle: 0.97, aim: 0.86, aggression: 0.76, recovery: 1.0, chase: 0.8, boostUse: 0.72 },
  { id: "ace", name: "Ace", throttle: 1.04, aim: 0.95, aggression: 0.92, recovery: 0.8, chase: 0.94, boostUse: 0.9 },
];

export const PROP_DEFS = {
  crate: {
    id: "crate",
    label: "Scrap Crate",
    hp: 20,
    radius: 24,
    color: "#a7744c",
    trim: "#f5d0a8",
    explosiveRadius: 0,
  },
  barrier: {
    id: "barrier",
    label: "Barrier Node",
    hp: 26,
    radius: 30,
    color: "#7d8fb6",
    trim: "#d9e3ff",
    explosiveRadius: 0,
  },
  canister: {
    id: "canister",
    label: "Fuel Canister",
    hp: 16,
    radius: 21,
    color: "#ff6b2d",
    trim: "#ffd8b8",
    explosiveRadius: 130,
  },
  tower: {
    id: "tower",
    label: "Power Relay",
    hp: 32,
    radius: 28,
    color: "#2ef0ff",
    trim: "#e0feff",
    explosiveRadius: 90,
  },
};

export const ANNOUNCER_STYLES = {
  neutral: { color: "#f4f8ff", accent: "#89a3d9" },
  warning: { color: "#ffd166", accent: "#ff6b2d" },
  danger: { color: "#ff7e8f", accent: "#ff4c63" },
  hype: { color: "#2ef0ff", accent: "#b7ff3b" },
};

export const DEFAULT_MENU_STATE = {
  aiFill: 2,
  botDifficulty: 1,
  modeId: "combatRace",
};
